Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-05, with the labels that each got.

#45 added missing SHA fields in bundle CRD
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
Labels: approved, lgtm, size/XS

#46 37259: changes to address restricted scc
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/M

#47 37644: revert crd back to v1alpha1
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#48 update readme and csv description
  README.md
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#49 37117: support upgrade operator 3.3 to 3.4
  Makefile
  README.md
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  deploy/operator.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values-metadata.yaml
  helm-charts/platform-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#50 update icp-audit-service and platform-api digests
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#51 37889: Canary Failure: Platform-api pod in image-pull-backoff
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  deploy/operator.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values-metadata.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#52 operator pod did not have enough memory allocated
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#53 37376: Update Helm foundation operators description and documentation
  README.md
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#54 37933: Helm foundation: Update productVersion metering annotations to…
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#55 change audit service resources in CR
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#56 update instance labels to match operand
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/S

#57 update annotation label
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#58 Cleanup
  deploy/operator.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/values-metadata.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#60 38052: Creating beta channel for cloud pak usage
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#61 fix broken image
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#62 add bump-up csv and protect csv scripts
  .githooks/pre-commit
  Makefile
  commonUtil/scripts/bump-up-csv.sh
  commonUtil/scripts/protect-csv.sh
  commonUtil/scripts/push-csv.sh
Labels: approved, lgtm, size/L

#63 pick up icp-platform-api 3.4.1 operand image
  .osdk-scorecard.yaml
  Makefile
  README.md
  commonUtil/scripts/protect-csv.sh
  deploy/olm-catalog/ibm-platform-api-operator/3.6.1/ibm-platform-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.1/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XL

#64 changed icp-platform-api digest for new Z build
  deploy/olm-catalog/ibm-platform-api-operator/3.6.1/ibm-platform-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#65 38341: Helm Foundation - Move CS 3.4.1 into beta channel
  deploy/olm-catalog/ibm-platform-api-operator/3.6.1/ibm-platform-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
