Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-11, with the labels that each got.

#115 42145: Upgrade helm-operator to v1.1.0
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#117 remove passwordrules crd
  deploy/crds/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/L

#118 fix image pullback error
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#122 fixing case linting errors
  README.md
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_platformapis.yaml
  config/crd/bases/operator.ibm.com_platformapis.yaml
  config/manifests/bases/ibm-platform-api-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#123 refactor kubebuilder format
  .githooks/pre-commit
  Makefile
  OWNERS
  PREVIOUS_VERSION
  RELEASE_VERSION
  SECURITY_CONTACTS
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/manifests/ibm-platform-api-operator_v1_serviceaccount.yaml
  common/Makefile.common.mk
  common/scripts/adjust_manifests.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/update_global_pull_secrets.sh
  commonUtil/resources/opencloud-operators.yaml
  commonUtil/scripts/bump-up-csv.sh
  commonUtil/scripts/generate-scorecard.sh
  commonUtil/scripts/protect-csv.sh
  commonUtil/scripts/push-csv.sh
  config/default/kustomization.yaml
  config/dev-default/kustomization.yaml
  config/dev-manager/kustomization.yaml
  config/dev-manager/manager.yaml
  config/development/kustomization.yaml
  config/development/manager_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-platform-api-operator.clusterserviceversion.yaml
  config/manifests/operandrequest.json
  config/rbac/kustomization.yaml
  config/rbac/serviceaccount.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XXL

#124 fix multi-arch image
  Makefile
Labels: approved, lgtm, size/S

#125 42802: fix manifest issue
  Makefile
  bundle/manifests/ibm-platform-api-operator_v1_serviceaccount.yaml
  common/scripts/update_catalogsource.sh
  config/rbac/kustomization.yaml
Labels: approved, lgtm, size/M

#126 removed old scorecard file, no longer being used
  .osdk-scorecard.yaml
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#127 upated README with new versions
  README.md
Labels: approved, lgtm, size/XS
