Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-07, with the labels that each got.

#68 bump CSV to 3.7.0
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XL

#70 add pod deletecollection permissions
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/role.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/M

#71 updates for 3.6.2
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XL

#72 merge changes from release 3.6
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#73 rollback beta to 3.6.1 to trigger build
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#74 promote 3.6.2 to beta channel
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#69 added new variables size and replicas to CR
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/operator.ibm.com_platformapis_crd.yaml
  helm-charts/platform-api/README.md
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values-metadata.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#75 update operator image as 3.6.2
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#76 updates to address security issues
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#78 backport changes in release-3.6 to master
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#77 need to use v0.17.0 base image to deal with helm force upgrade issue …
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#80 update 3.6.2 operator image digest
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#81 promote 3.6.2 to beta
  deploy/olm-catalog/ibm-platform-api-operator/3.6.2/ibm-platform-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#83 39777: promote ibm-platform-api-operator:3.6.2 to stable-v1
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#84 39777: promote ibm-platform-api-operator:3.6.2 to stable-v1
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#82 reduce resource footprint
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#79 patch existing platform-api CRs during upgrade
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M
