Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-08, with the labels that each got.

#85 integrate with new CICD pipeline
  Makefile
  commonUtil/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#86 removed productVersion annotation
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#87 40023 - downgrade manifest-tool to v0.7.0
  Makefile
Labels: approved, lgtm, size/XS

#88 remove quay credentials from manifest-tool
  Makefile
  README.md
Labels: approved, lgtm, size/XS

#89 improve dev workflow
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/L

#90 removing initContainer and addressing linting error
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/M

#91 40210: add pod anit-affinity for HA support
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#92 update icp-platform-api image
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#95 40265 - update icp-audit-service image
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#93 updated operand digest
  deploy/olm-catalog/ibm-platform-api-operator/3.7.0/ibm-platform-api-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#96 bump csv version and add multi-arch support
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-platform-api-operator/3.7.1/ibm-platform-api-operator.v3.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.7.1/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XL

#97 added multi-arch support labels
  deploy/olm-catalog/ibm-platform-api-operator/3.7.1/ibm-platform-api-operator.v3.7.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#98 40594: Canary Failure: helm-repo and catalog-ui not running on OCP 4.6
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XS
