Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-10, with the labels that each got.

#108 bump csv to 3.8.0
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XL

#107 added 2 new environment variables to platform-api container,
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#110 41997: switch to use audit logging rsyslog sidecar
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  hack/csv_images.sed
  helm-charts/platform-api/README.md
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XL

#111 41512: remove hard-corded ibm-common-services namespace
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role_binding.yaml
  helm-charts/platform-api/README.md
  helm-charts/platform-api/templates/platform-api-configmap.yaml
  helm-charts/platform-api/templates/platform-api-ingress.yaml
  helm-charts/platform-api/values-metadata.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#112 update audit-syslog image
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#114 change passwordrules api group to operator.ibm.com
  deploy/crds/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/ibm-platform-api-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.8.0/operator.ibm.com_passwordrules_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  helm-charts/platform-api/templates/password-rule-crd.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/L
