Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-04, with the labels that each got.

#23 fix push-multi-arch target to push with git commit tag
  .gitignore
  Makefile
Labels: approved, lgtm, size/XS

#24 flesh out validation definitions
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
Labels: approved, lgtm, size/M

#25 3.5.0->3.6.0
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#26 Crdquickfix
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
Labels: approved, lgtm, size/L

#27 allow reading configmaps to use with icp-platform-api:3.4.0
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/role.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#28 set resource requests equal to limits to avoid OOM
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#29 37142: add imageRegistry for CICD
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#31 audit service has new requirements
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#32 36969: add operator dependencies
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#33 add dev channel
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#34 37228: clean up unnecessarily exposed configurations
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1_platformapi_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  helm-charts/platform-api/templates/platform-api-configmap.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#36 case bundle changes
  Makefile
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/0.0.1/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/0.0.1/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/password-rule-crd.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/templates/platform-api-ingress.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/templates/platform-api-service.yaml
  helm-charts/platform-api/values-metadata.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/L

#37 fixing case bundle build failure
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  helm-charts/platform-api/templates/platform-api-service.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#38 add missing permissions for pm update-secret command
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/M

#39 operand had updated RBAC, but operator was not updated
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#40 fixes to prepare for integration build
  Makefile
  deploy/crds/operator.ibm.com_v1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/operator.ibm.com_platformapis_crd.yaml
  deploy/operator.yaml
  helm-charts/platform-api/templates/platform-api-service.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#41 remove nodeSelector
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#42 37418: Remediate package vulnerability in ibmcom-amd64
  build/Dockerfile
Labels: approved, lgtm, size/XS

#43 37561: Remediate package vulnerability in ibmcom-ppc64le
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#44 change image tag references to digest
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/ibm_cloud_pak/qualification.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/L
