Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-03, with the labels that each got.

#3 Refactor platform api operator
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/generate-scorecard.sh
  deploy/crds/operator.ibm.com_v1alpha1_passwordrule_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/0.0.1/ibm-platform-api-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  hack/ibmcloud-cluster-info.yaml
  helm-charts/platform-api/README.md
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-cluster-ca-cert.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/templates/platform-api-scc.yaml
  helm-charts/platform-api/values-metadata.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/L

#4 changes to support removal of ibmcloud-cluster-info
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/0.0.1/ibm-platform-api-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#6 add metering and health check annotations
  commonUtil/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/0.0.1/ibm-platform-api-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#7 fix rbac issue for password management migration
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/XS

#8 RH cert labels
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/M

#9 update csv version to 3.5.0
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/generate-scorecard.sh
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_platformapis_crd.yaml
Labels: approved, lgtm, size/L

#10 change current csv to 3.5.0
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#11 update healthcheck dependencies annotation
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#12 fixing RH certificatoin metadata linting issues
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_platformapis_crd.yaml
Labels: approved, lgtm, size/S

#13 36525 - target namespace not available in new helm release wizard
  Makefile
  deploy/crds/operator.ibm.com_passwordrules_crd.yaml
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/M

#14 fix platform-api-sa cannot access clusterrolebindings
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/S

#15 update repository field in csv
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#16 update containerImage field in csv
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#17 refactor passwordrule crd to address scorecard issue
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/operator.ibm.com_passwordrules_crd.yaml
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_passwordrule_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_passwordrules_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  helm-charts/platform-api/templates/password-management-migration.yaml
  helm-charts/platform-api/templates/password-rule-crd.yaml
  helm-charts/platform-api/templates/platform-api-configmap.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
  helm-charts/platform-api/templates/platform-api-ingress.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
  helm-charts/platform-api/templates/platform-api-service.yaml
Labels: approved, lgtm, size/L

#18 fix scorecard
  deploy/crds/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/operator.ibm.com_platformapis_crd.yaml
Labels: approved, lgtm, size/M

#19 add ReplicaSet in resources list
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#20 update icp-audit-service:3.3.1 to 3.4.0
  deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.5.0/ibm-platform-api-operator.v3.5.0.clusterserviceversion.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#21 update icp-audit-service:3.3.1 to 3.4.0
  helm-charts/platform-api/ibm_cloud_pak/manifest.yaml
Labels: approved, lgtm, size/S

#22 add README.md
  README.md
  SECURITY_CONTACTS
Labels: approved, lgtm, size/M
