Repository IBM/ibm-platform-api-operator, pull requests merged in 2020-09, with the labels that each got.

#100 40607: reduce operator cpu request and limit
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.7.1/ibm-platform-api-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
Labels: approved, lgtm, size/S

#101 update operand image digest
  deploy/olm-catalog/ibm-platform-api-operator/3.7.1/ibm-platform-api-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#102 updated platform-api operand digest
  deploy/olm-catalog/ibm-platform-api-operator/3.7.1/ibm-platform-api-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#103 update csv to 3.7.2
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-platform-api-operator/3.7.2/ibm-platform-api-operator.v3.7.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-platform-api-operator/3.7.2/operator.ibm.com_platformapis_crd.yaml
  deploy/olm-catalog/ibm-platform-api-operator/ibm-platform-api-operator.package.yaml
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XL

#104 updated platform-api operand to a7cb08
  deploy/olm-catalog/ibm-platform-api-operator/3.7.2/ibm-platform-api-operator.v3.7.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#105 41418: use soft pod anti-affinity policy
  Makefile
  README.md
  hack/csv_images.sed
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/M

#106 41421: upgrade helm operator to fix va scan issue
  build/Dockerfile
  build/Dockerfile.ppc64le
Labels: approved, lgtm, size/XS
