Repository IBM/ibm-platform-api-operator, pull requests merged in 2021-02, with the labels that each got.

#142 changed environment variable names for operands
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/development/manager_patch.yaml
  config/manager/manager.yaml
  helm-charts/platform-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#143 port CICD operand digest auto update changes from master
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/development/manager_patch.yaml
  config/manager/manager.yaml
  helm-charts/platform-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#144 updated icp-platform-api to 3.7.0
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/development/manager_patch.yaml
  config/manager/manager.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/XS

#145 updated kubeVersion for chart to fix case bundle linting issue;
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XS

#146 updates to fix case bundle linting issues
  README.md
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/templates/platform-api-ingress.yaml
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/M

#147 restart PROW build
  README.md
Labels: approved, lgtm, size/XS

#148 update audit-syslog-service:1.0.5
  README.md
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/development/manager_patch.yaml
  config/manager/manager.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#149 44708: platform api CSV missing replaces statement
  PREVIOUS_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/scripts/adjust_manifests.sh
Labels: approved, lgtm, size/XS

#150 44717: address certification assessment gaps
  README.md
Labels: approved, lgtm, size/M
