Repository IBM/ibm-platform-api-operator, pull requests merged in 2021-01, with the labels that each got.

#131 updated deprecated node affinity label from beta.kubernetes.io/arch t…
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#132 updated operator-sdk version from v1.2.0 to v1.3.0
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/install-operator-sdk.sh
  config/manifests/bases/ibm-platform-api-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#134 updated operand digest
  Makefile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/S

#133 general version updates for 3.6 EUS release
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/install-operator-sdk.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-platform-api-operator.clusterserviceversion.yaml
  helm-charts/platform-api/Chart.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#135 updated README with new operator version
  README.md
Labels: approved, lgtm, size/XS

#136 43677: Add PodTopologyContraint to the Pod Spec in the Deployment
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#137 43677: Add PodTopologyContraint to the Pod Spec in the Deployment - release 3.8
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#138 changed script that adjusted replaces field in CSV from adjusting the
  Makefile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/scripts/adjust_manifests.sh
Labels: approved, lgtm, size/S

#139 removed hard coded ibm-common-services namespace
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, lgtm, size/XS

#140 44089: create own certificate
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  helm-charts/platform-api/templates/platform-api-cert.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#141 44089: create own certificate
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  helm-charts/platform-api/templates/platform-api-cert.yaml
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M
