Repository IBM/ibm-platform-api-operator, pull requests merged in 2021-11, with the labels that each got.

#171 Bump eus version
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/Makefile.common.mk
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/S

#173 updated version to 3.16.0
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/M

#172 updated operator-sdk to v1.14.0
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  OWNERS
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_platformapis.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/manifests/bases/ibm-platform-api-operator.clusterserviceversion.yaml
  helm-charts/platform-api/Chart.yaml
Labels: size/XL, approved, lgtm

#174 replaced deprecated affinity key for lint error
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#175 add user 1001 for Dockerfile
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, lgtm, size/S

#177 updated operator-sdk to v1.15.0
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: approved, lgtm, size/S

#176 updated operator-sdk to v1.15.0
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  helm-charts/platform-api/Chart.yaml
Labels: size/XL, approved, lgtm
