Repository IBM/ibm-platform-api-operator, pull requests merged in 2022-04, with the labels that each got.

#195 add base_images.json file
  base_images.json
Labels: approved, lgtm, size/XS

#197 bump platform-api version to 3.20.0
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/S

#196 [WIP] remove clusterrole for catalog-ui
  helm-charts/platform-api/templates/platform-api-rbac.yaml
Labels: approved, size/M

#198 migrate to ICR
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-platform-api-operator.clusterserviceversion.yaml
  hack/csv_images.sed
  helm-charts/platform-api/README.md
  helm-charts/platform-api/values.yaml
Labels: approved, lgtm, size/M

#199 update multi-arch build
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, size/M
