Repository IBM/ibm-platform-api-operator, pull requests merged in 2022-03, with the labels that each got.

#193 create next-csv.sh & update version to 3.19.0
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/scripts/next-csv.sh
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/M

#194 opt in for auto updates for the helm operator image
  Dockerfile
  Makefile
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/XS

#192 add pre upgrade hook
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/development/manager_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  helm-charts/platform-api/templates/pre-upgrade-job.yaml
  helm-charts/platform-api/templates/pre-upgrade-script-configmap.yaml
  helm-charts/platform-api/values.yaml
  watches.yaml
Labels: approved, size/L, lgtm
