Repository IBM/ibm-platform-api-operator, pull requests merged in 2022-01, with the labels that each got.

#179 added missing keywords from verified category for case linting
  Dockerfile.ppc64le
  Dockerfile.s390x
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/XS

#181 update the copyrights for 2022
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/Makefile.common.mk
  common/scripts/adjust_manifests.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/update_catalogsource.sh
  common/scripts/update_global_pull_secrets.sh
  helm-charts/platform-api/LICENSES/LICENSE_en
  helm-charts/platform-api/README.md
  helm-charts/platform-api/RELEASENOTES.md
  helm-charts/platform-api/templates/_helpers.tpl
  helm-charts/platform-api/values-metadata.yaml
Labels: approved, size/M

#180 increase cpu request
  Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#182 update the copyrights for 2022 in EUS
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/Makefile.common.mk
  common/scripts/adjust_manifests.sh
  common/scripts/config_docker.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint-csv.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/update_catalogsource.sh
  common/scripts/update_global_pull_secrets.sh
  helm-charts/platform-api/LICENSES/LICENSE_en
  helm-charts/platform-api/README.md
  helm-charts/platform-api/RELEASENOTES.md
  helm-charts/platform-api/templates/_helpers.tpl
  helm-charts/platform-api/values-metadata.yaml
Labels: approved, lgtm, size/M
