Repository IBM/ibm-platform-api-operator, pull requests merged in 2022-07, with the labels that each got.

#206 replaced configmaps by leases for leader election
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/adjust_manifests.sh
  config/rbac/leader_election_role.yaml
Labels: approved, lgtm, size/M

#207 replaced configmaps by leases for leader election
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/adjust_manifests.sh
  config/rbac/leader_election_role.yaml
Labels: approved, lgtm, size/M

#208 changed liveness and readiness probes
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/S

#210 changed timeoutSeconds for probes to 30
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#212 bump versioin to 3.21.2
  PREVIOUS_VERSION
  README.md
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/S
