Repository IBM/ibm-platform-api-operator, pull requests merged in 2023-01, with the labels that each got.

#222 update readiness and liveness probes to use https
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#224 Revert "update readiness and liveness probes to use https"
  helm-charts/platform-api/templates/platform-api-deployment.yaml
Labels: approved, lgtm, size/XS

#227 bump version for 3.19.8
  PREVIOUS_VERSION
  README.md
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/S

#229 new artifactory image endpoint (platform api)
  Dockerfile
  Makefile
  common/scripts/config_docker.sh
  common/scripts/update_global_pull_secrets.sh
  config/development/manager_patch.yaml
  hack/csv_images.sed
Labels: approved, lgtm, size/M

#230 [ltsr] new artifactory image endpoint (platform api)
  Dockerfile
  Makefile
  common/scripts/config_docker.sh
  common/scripts/update_global_pull_secrets.sh
  config/development/manager_patch.yaml
  hack/csv_images.sed
Labels: approved, lgtm, size/M

#231 bump to v3.25.1 for v3.23.1
  PREVIOUS_VERSION
  RELEASE_VERSION
  bundle/manifests/ibm-platform-api-operator.clusterserviceversion.yaml
  common/scripts/next-csv.sh
  helm-charts/platform-api/Chart.yaml
Labels: approved, lgtm, size/M
